language: php

php:
  - 5.3
  - 5.4

before_script:
    - "mysql -e 'create database `archivemytweetssymfony`;'"
    - "mysql archivemytweetssymfony < Tests/Resources/data/tweets.sql"
    - mv src/Wysow/ArchiveMyTweetsBundle/Tests/Functional/config/parameters.yml.dist src/Wysow/ArchiveMyTweetsBundle/Tests/Functional/config/parameters.yml
    - composer self-update
    - composer install --dev --prefer-source

script: phpunit -c app --coverage-text
