---
language: php
php:
- 5.3
- 5.4
before_script:
- echo -e "Host pagoda.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host git.pagoda.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mysql -e 'create database `archivemytweetssymfony`;'
- mysql archivemytweetssymfony < src/Wysow/ArchiveMyTweetsBundle/Tests/Resources/data/tweets.sql
- mv src/Wysow/ArchiveMyTweetsBundle/Tests/Functional/config/parameters.yml.dist src/Wysow/ArchiveMyTweetsBundle/Tests/Functional/config/parameters.yml
- composer self-update
- composer install --dev --prefer-source
script: phpunit -c app --coverage-text
after_success:
- chmod +x bin/after_success
- ./bin/after_success
env:
  global:
  - secure: ! 'R680anVBvOx3kuVVTZLqnu4yYd4pvIB6nS4DzpfYIQd7UQ6w9vF9ToNtvSOX

      U/mF/UTQBsGdl5cSysq4pEOG36V7rG4LWYbOPyCEn0lWenw+S3l0VyHKrxs/

      vnSyNB0sSQalhd/FF1RjtVg4rqeLLwbujSfq10Ra5DYvlaZD2L0='
  - secure: ! 'J+ERUUoNc6wsJnRH/tBUloH85ZNnmccUDvx6TJFfD8XwxsP+GLQTvwvEqTvP

      UmyUHueVnnVEmoHJv+137MLPsHp2WTVfoiM2KmsBV5GkbbBIUxxFAU6A+nSy

      Fnd8tl2iGOvPwsYwxxRppU5nfKxlKNoDjOcktIMPBEeLSK6w08c='
