language: php

php:
  - 5.3
  - 5.4

before_script:
    - "mysql -e 'create database `archivemytweetssymfony`;'"
    - mv Tests/Functional/config/parameters.yml.dist Tests/Functional/config/parameters.yml
    - composer self-update
    - composer install --dev --prefer-source

script: phpunit --coverage-text
