<?php

namespace Wysow\ArchiveMyTweetsBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    public function findAllByCreatedAtDesc()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.createdAt', 'DESC');

        return $qb->getQuery()->execute();
    }
    public function getTweetsByMonths()
    {
        $this->addDoctrineExtensions();

        $qb = $this->createQueryBuilder('t')
            ->select('YEAR(t.createdAt) as y, MONTH(t.createdAt) as m, count(t.id) as total')
            ->groupBy('y,m')
            ->orderBy('t.createdAt', 'DESC');

        return $qb->getQuery()->execute();
    }

    public function getTotalClients()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('count(distinct t.source) as total');

        return $qb->getQuery()->getSingleResult()['total'];
    }

    public function getClients()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.source, count(t.id) as total')
            ->groupBy('t.source')
            ->orderBy('total', 'DESC');

        return $qb->getQuery()->execute();
    }

    public function findByYearAndMonth($year, $month)
    {
        $this->addDoctrineExtensions();

        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('YEAR(t.createdAt) = :year')
            ->andWhere('MONTH(t.createdAt) = :month')
            ->orderBy('t.createdAt', 'DESC')
            ->setParameter('year', $year)
            ->setParameter('month', $month);

        return $qb->getQuery()->execute();
    }

    private function addDoctrineExtensions()
    {
        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
    }
}